// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	apifarm "apifarm/src"

	mock "github.com/stretchr/testify/mock"
)

// DataLoader is an autogenerated mock type for the DataLoader type
type DataLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *DataLoader) Load(_a0 string) []apifarm.VideoGame {
	ret := _m.Called(_a0)

	var r0 []apifarm.VideoGame
	if rf, ok := ret.Get(0).(func(string) []apifarm.VideoGame); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apifarm.VideoGame)
		}
	}

	return r0
}
