// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	apifarm "apifarm/src"

	mock "github.com/stretchr/testify/mock"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// GetAllVideoGames provides a mock function with given fields:
func (_m *DB) GetAllVideoGames() []apifarm.VideoGame {
	ret := _m.Called()

	var r0 []apifarm.VideoGame
	if rf, ok := ret.Get(0).(func() []apifarm.VideoGame); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apifarm.VideoGame)
		}
	}

	return r0
}
