// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Response is an autogenerated mock type for the Response type
type Response struct {
	mock.Mock
}

// OkText provides a mock function with given fields: _a0
func (_m *Response) OkText(_a0 string) {
	_m.Called(_a0)
}
