AllCops:
  NewCops: enable

Layout/EndOfLine:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true